# Job

parameters:
  name: ''
  vmImage: ''
  buildConfiguration: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  variables:
    buildConfiguration: ${{ parameters.buildConfiguration }}
  steps:
  - template: ../install.yaml
  - template: ../build.yaml
  - template: ../run-tests.yaml
  - ${{ if eq(parameters['buildConfiguration'], 'Release') && not eq(variables['Build.Reason'], 'PullRequest') }}:
    - template: ../publish.yaml
